[package]
name = "kclvm-utils"
version = "0.8.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fslock = "0.2.1"
