name: build-and-test-ubuntu
on: ["push", "pull_request"]
jobs:
  build-and-test:
    # Ref: https://github.com/actions/runner-images/tree/main/images/linux
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      # Prerequisite

      - name: Install Python3 and LLVM
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl make
          sudo apt-get install python3 python3-pip -y
          sudo apt-get install -y clang-12 lld-12
          sudo ln -sf /usr/bin/clang-12 /usr/bin/clang
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73
          override: true
          components: clippy, rustfmt
      - name: Code format check
        working-directory: ./kclvm
        run: cargo fmt --check
        shell: bash
      - name: Code clippy check
        working-directory: ./kclvm
        run: cargo clippy --no-deps -r
        shell: bash
      - name: Grammar test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make test-grammar
        shell: bash
      - name: Runtime test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make test-runtime
        shell: bash
      - name: Install kpm
        run: go install kcl-lang.io/kpm@latest

      - name: Unit test
        working-directory: ./kclvm
        run: export PATH=$PATH:$PWD/../_build/dist/ubuntu/kclvm/bin && make install-rustc-wasm && make && make codecov-lcov
        shell: bash

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./kclvm/.kclvm_cov/lcov.info

      - uses: actions/upload-artifact@v3
        with:
          name: kcl-linux-amd64
          path: _build/dist/ubuntu/kclvm
